services:
  # 宇宙一：Agent 智能制版引擎
  ai_server:
    build: .
    container_name: ai-server
    env_file: [ .env ]
    environment:
      POSTGRES_HOST: postgres

    volumes:
      - ./data:/app/data
    ports:
      # 打开大门，让宿主机上的 OpenResty 能把前端请求转进来
      - "8001:8001"
    networks:
      - network

  # 宇宙二：Celery 工作进程 (它不需要开端口，默默干活就行)
  celery_worker:
    build: .
    container_name: celery-worker
    env_file: [ .env ]
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ./data:/app/data
    networks:
      - network
    command: celery -A core.celery_app worker --loglevel=info

networks:
  network:
    external: true
